/* tslint:disable */
/* eslint-disable */
/**
 * OpenHPC
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VMCreatedInfo
 */
export interface VMCreatedInfo {
    /**
     * 
     * @type {string}
     * @memberof VMCreatedInfo
     */
    cid: string;
    /**
     * 
     * @type {string}
     * @memberof VMCreatedInfo
     */
    rdsAt: string;
    /**
     * 
     * @type {string}
     * @memberof VMCreatedInfo
     */
    token: string;
    /**
     * 
     * @type {string}
     * @memberof VMCreatedInfo
     */
    ssh: string;
    /**
     * 
     * @type {string}
     * @memberof VMCreatedInfo
     */
    http: string;
    /**
     * 
     * @type {string}
     * @memberof VMCreatedInfo
     */
    svcTag: string;
    /**
     * 
     * @type {string}
     * @memberof VMCreatedInfo
     */
    sc: string;
}

/**
 * Check if a given object implements the VMCreatedInfo interface.
 */
export function instanceOfVMCreatedInfo(value: object): value is VMCreatedInfo {
    if (!('cid' in value) || value['cid'] === undefined) return false;
    if (!('rdsAt' in value) || value['rdsAt'] === undefined) return false;
    if (!('token' in value) || value['token'] === undefined) return false;
    if (!('ssh' in value) || value['ssh'] === undefined) return false;
    if (!('http' in value) || value['http'] === undefined) return false;
    if (!('svcTag' in value) || value['svcTag'] === undefined) return false;
    if (!('sc' in value) || value['sc'] === undefined) return false;
    return true;
}

export function VMCreatedInfoFromJSON(json: any): VMCreatedInfo {
    return VMCreatedInfoFromJSONTyped(json, false);
}

export function VMCreatedInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): VMCreatedInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'cid': json['cid'],
        'rdsAt': json['rds_at'],
        'token': json['token'],
        'ssh': json['ssh'],
        'http': json['http'],
        'svcTag': json['svc_tag'],
        'sc': json['sc'],
    };
}

export function VMCreatedInfoToJSON(json: any): VMCreatedInfo {
    return VMCreatedInfoToJSONTyped(json, false);
}

export function VMCreatedInfoToJSONTyped(value?: VMCreatedInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cid': value['cid'],
        'rds_at': value['rdsAt'],
        'token': value['token'],
        'ssh': value['ssh'],
        'http': value['http'],
        'svc_tag': value['svcTag'],
        'sc': value['sc'],
    };
}

