/* tslint:disable */
/* eslint-disable */
/**
 * OpenHPC
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VMDelReq
 */
export interface VMDelReq {
    /**
     * 
     * @type {string}
     * @memberof VMDelReq
     */
    provider: string;
    /**
     * 
     * @type {string}
     * @memberof VMDelReq
     */
    id: string;
}

/**
 * Check if a given object implements the VMDelReq interface.
 */
export function instanceOfVMDelReq(value: object): value is VMDelReq {
    if (!('provider' in value) || value['provider'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function VMDelReqFromJSON(json: any): VMDelReq {
    return VMDelReqFromJSONTyped(json, false);
}

export function VMDelReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): VMDelReq {
    if (json == null) {
        return json;
    }
    return {
        
        'provider': json['provider'],
        'id': json['id'],
    };
}

export function VMDelReqToJSON(json: any): VMDelReq {
    return VMDelReqToJSONTyped(json, false);
}

export function VMDelReqToJSONTyped(value?: VMDelReq | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'provider': value['provider'],
        'id': value['id'],
    };
}

