/* tslint:disable */
/* eslint-disable */
/**
 * OpenHPC
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VMListItemMount
 */
export interface VMListItemMount {
    /**
     * 
     * @type {string}
     * @memberof VMListItemMount
     */
    host: string;
    /**
     * 
     * @type {string}
     * @memberof VMListItemMount
     */
    container: string;
    /**
     * 
     * @type {boolean}
     * @memberof VMListItemMount
     */
    readonly: boolean;
}

/**
 * Check if a given object implements the VMListItemMount interface.
 */
export function instanceOfVMListItemMount(value: object): value is VMListItemMount {
    if (!('host' in value) || value['host'] === undefined) return false;
    if (!('container' in value) || value['container'] === undefined) return false;
    if (!('readonly' in value) || value['readonly'] === undefined) return false;
    return true;
}

export function VMListItemMountFromJSON(json: any): VMListItemMount {
    return VMListItemMountFromJSONTyped(json, false);
}

export function VMListItemMountFromJSONTyped(json: any, ignoreDiscriminator: boolean): VMListItemMount {
    if (json == null) {
        return json;
    }
    return {
        
        'host': json['host'],
        'container': json['container'],
        'readonly': json['readonly'],
    };
}

export function VMListItemMountToJSON(json: any): VMListItemMount {
    return VMListItemMountToJSONTyped(json, false);
}

export function VMListItemMountToJSONTyped(value?: VMListItemMount | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'host': value['host'],
        'container': value['container'],
        'readonly': value['readonly'],
    };
}

