/* tslint:disable */
/* eslint-disable */
/**
 * OpenHPC
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VMListItem } from './VMListItem';
import {
    VMListItemFromJSON,
    VMListItemFromJSONTyped,
    VMListItemToJSON,
    VMListItemToJSONTyped,
} from './VMListItem';

/**
 * 
 * @export
 * @interface VMListProvider
 */
export interface VMListProvider {
    /**
     * 
     * @type {string}
     * @memberof VMListProvider
     */
    provider: string;
    /**
     * 
     * @type {Array<VMListItem>}
     * @memberof VMListProvider
     */
    containers: Array<VMListItem>;
}

/**
 * Check if a given object implements the VMListProvider interface.
 */
export function instanceOfVMListProvider(value: object): value is VMListProvider {
    if (!('provider' in value) || value['provider'] === undefined) return false;
    if (!('containers' in value) || value['containers'] === undefined) return false;
    return true;
}

export function VMListProviderFromJSON(json: any): VMListProvider {
    return VMListProviderFromJSONTyped(json, false);
}

export function VMListProviderFromJSONTyped(json: any, ignoreDiscriminator: boolean): VMListProvider {
    if (json == null) {
        return json;
    }
    return {
        
        'provider': json['provider'],
        'containers': ((json['containers'] as Array<any>).map(VMListItemFromJSON)),
    };
}

export function VMListProviderToJSON(json: any): VMListProvider {
    return VMListProviderToJSONTyped(json, false);
}

export function VMListProviderToJSONTyped(value?: VMListProvider | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'provider': value['provider'],
        'containers': ((value['containers'] as Array<any>).map(VMListItemToJSON)),
    };
}

