/* tslint:disable */
/* eslint-disable */
/**
 * OpenHPC
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VMReqAvailImage
 */
export interface VMReqAvailImage {
    /**
     * 
     * @type {string}
     * @memberof VMReqAvailImage
     */
    image: string;
    /**
     * 
     * @type {string}
     * @memberof VMReqAvailImage
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof VMReqAvailImage
     */
    displayName: string;
}

/**
 * Check if a given object implements the VMReqAvailImage interface.
 */
export function instanceOfVMReqAvailImage(value: object): value is VMReqAvailImage {
    if (!('image' in value) || value['image'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    return true;
}

export function VMReqAvailImageFromJSON(json: any): VMReqAvailImage {
    return VMReqAvailImageFromJSONTyped(json, false);
}

export function VMReqAvailImageFromJSONTyped(json: any, ignoreDiscriminator: boolean): VMReqAvailImage {
    if (json == null) {
        return json;
    }
    return {
        
        'image': json['image'],
        'description': json['description'],
        'displayName': json['display_name'],
    };
}

export function VMReqAvailImageToJSON(json: any): VMReqAvailImage {
    return VMReqAvailImageToJSONTyped(json, false);
}

export function VMReqAvailImageToJSONTyped(value?: VMReqAvailImage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'image': value['image'],
        'description': value['description'],
        'display_name': value['displayName'],
    };
}

