/* tslint:disable */
/* eslint-disable */
/**
 * OpenHPC
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VMReqAvailImage } from './VMReqAvailImage';
import {
    VMReqAvailImageFromJSON,
    VMReqAvailImageFromJSONTyped,
    VMReqAvailImageToJSON,
    VMReqAvailImageToJSONTyped,
} from './VMReqAvailImage';
import type { VMReqAvailGPU } from './VMReqAvailGPU';
import {
    VMReqAvailGPUFromJSON,
    VMReqAvailGPUFromJSONTyped,
    VMReqAvailGPUToJSON,
    VMReqAvailGPUToJSONTyped,
} from './VMReqAvailGPU';

/**
 * 
 * @export
 * @interface VMReqAvailResources
 */
export interface VMReqAvailResources {
    /**
     * 
     * @type {Array<VMReqAvailImage>}
     * @memberof VMReqAvailResources
     */
    images: Array<VMReqAvailImage>;
    /**
     * 
     * @type {Array<VMReqAvailGPU>}
     * @memberof VMReqAvailResources
     */
    gpus: Array<VMReqAvailGPU>;
    /**
     * 
     * @type {Array<string>}
     * @memberof VMReqAvailResources
     */
    providers: Array<string>;
}

/**
 * Check if a given object implements the VMReqAvailResources interface.
 */
export function instanceOfVMReqAvailResources(value: object): value is VMReqAvailResources {
    if (!('images' in value) || value['images'] === undefined) return false;
    if (!('gpus' in value) || value['gpus'] === undefined) return false;
    if (!('providers' in value) || value['providers'] === undefined) return false;
    return true;
}

export function VMReqAvailResourcesFromJSON(json: any): VMReqAvailResources {
    return VMReqAvailResourcesFromJSONTyped(json, false);
}

export function VMReqAvailResourcesFromJSONTyped(json: any, ignoreDiscriminator: boolean): VMReqAvailResources {
    if (json == null) {
        return json;
    }
    return {
        
        'images': ((json['images'] as Array<any>).map(VMReqAvailImageFromJSON)),
        'gpus': ((json['gpus'] as Array<any>).map(VMReqAvailGPUFromJSON)),
        'providers': json['providers'],
    };
}

export function VMReqAvailResourcesToJSON(json: any): VMReqAvailResources {
    return VMReqAvailResourcesToJSONTyped(json, false);
}

export function VMReqAvailResourcesToJSONTyped(value?: VMReqAvailResources | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'images': ((value['images'] as Array<any>).map(VMReqAvailImageToJSON)),
        'gpus': ((value['gpus'] as Array<any>).map(VMReqAvailGPUToJSON)),
        'providers': value['providers'],
    };
}

