/* tslint:disable */
/* eslint-disable */
/**
 * OpenHPC
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VMReqAvailGPU
 */
export interface VMReqAvailGPU {
    /**
     * 
     * @type {string}
     * @memberof VMReqAvailGPU
     */
    displayName: string;
    /**
     * 
     * @type {number}
     * @memberof VMReqAvailGPU
     */
    gpuId: number;
}

/**
 * Check if a given object implements the VMReqAvailGPU interface.
 */
export function instanceOfVMReqAvailGPU(value: object): value is VMReqAvailGPU {
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    if (!('gpuId' in value) || value['gpuId'] === undefined) return false;
    return true;
}

export function VMReqAvailGPUFromJSON(json: any): VMReqAvailGPU {
    return VMReqAvailGPUFromJSONTyped(json, false);
}

export function VMReqAvailGPUFromJSONTyped(json: any, ignoreDiscriminator: boolean): VMReqAvailGPU {
    if (json == null) {
        return json;
    }
    return {
        
        'displayName': json['display_name'],
        'gpuId': json['gpu_id'],
    };
}

export function VMReqAvailGPUToJSON(json: any): VMReqAvailGPU {
    return VMReqAvailGPUToJSONTyped(json, false);
}

export function VMReqAvailGPUToJSONTyped(value?: VMReqAvailGPU | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'display_name': value['displayName'],
        'gpu_id': value['gpuId'],
    };
}

