/* tslint:disable */
/* eslint-disable */
/**
 * OpenHPC
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VMReqGPU
 */
export interface VMReqGPU {
    /**
     * 
     * @type {boolean}
     * @memberof VMReqGPU
     */
    all: boolean;
    /**
     * 
     * @type {Array<number>}
     * @memberof VMReqGPU
     */
    ids: Array<number>;
}

/**
 * Check if a given object implements the VMReqGPU interface.
 */
export function instanceOfVMReqGPU(value: object): value is VMReqGPU {
    if (!('all' in value) || value['all'] === undefined) return false;
    if (!('ids' in value) || value['ids'] === undefined) return false;
    return true;
}

export function VMReqGPUFromJSON(json: any): VMReqGPU {
    return VMReqGPUFromJSONTyped(json, false);
}

export function VMReqGPUFromJSONTyped(json: any, ignoreDiscriminator: boolean): VMReqGPU {
    if (json == null) {
        return json;
    }
    return {
        
        'all': json['all'],
        'ids': json['ids'],
    };
}

export function VMReqGPUToJSON(json: any): VMReqGPU {
    return VMReqGPUToJSONTyped(json, false);
}

export function VMReqGPUToJSONTyped(value?: VMReqGPU | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'all': value['all'],
        'ids': value['ids'],
    };
}

