/* tslint:disable */
/* eslint-disable */
/**
 * OpenHPC
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VMTokenReq
 */
export interface VMTokenReq {
    /**
     * 
     * @type {string}
     * @memberof VMTokenReq
     */
    provider: string;
    /**
     * 
     * @type {string}
     * @memberof VMTokenReq
     */
    id: string;
}

/**
 * Check if a given object implements the VMTokenReq interface.
 */
export function instanceOfVMTokenReq(value: object): value is VMTokenReq {
    if (!('provider' in value) || value['provider'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function VMTokenReqFromJSON(json: any): VMTokenReq {
    return VMTokenReqFromJSONTyped(json, false);
}

export function VMTokenReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): VMTokenReq {
    if (json == null) {
        return json;
    }
    return {
        
        'provider': json['provider'],
        'id': json['id'],
    };
}

export function VMTokenReqToJSON(json: any): VMTokenReq {
    return VMTokenReqToJSONTyped(json, false);
}

export function VMTokenReqToJSONTyped(value?: VMTokenReq | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'provider': value['provider'],
        'id': value['id'],
    };
}

