/* tslint:disable */
/* eslint-disable */
/**
 * OpenHPC
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface VMUpgradeReq
 */
export interface VMUpgradeReq {
    /**
     * 
     * @type {string}
     * @memberof VMUpgradeReq
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof VMUpgradeReq
     */
    shm: number;
    /**
     * 
     * @type {string}
     * @memberof VMUpgradeReq
     */
    provider: string;
}

/**
 * Check if a given object implements the VMUpgradeReq interface.
 */
export function instanceOfVMUpgradeReq(value: object): value is VMUpgradeReq {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('shm' in value) || value['shm'] === undefined) return false;
    if (!('provider' in value) || value['provider'] === undefined) return false;
    return true;
}

export function VMUpgradeReqFromJSON(json: any): VMUpgradeReq {
    return VMUpgradeReqFromJSONTyped(json, false);
}

export function VMUpgradeReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): VMUpgradeReq {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'shm': json['shm'],
        'provider': json['provider'],
    };
}

export function VMUpgradeReqToJSON(json: any): VMUpgradeReq {
    return VMUpgradeReqToJSONTyped(json, false);
}

export function VMUpgradeReqToJSONTyped(value?: VMUpgradeReq | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'shm': value['shm'],
        'provider': value['provider'],
    };
}

